import './globals.css'
import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import Content from './Content'


const quicksand = Quicksand( { subsets: ['latin'] } )

export const metadata: Metadata = {
  title: 'Applicant Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout ( {
  children,
}: {
  children: React.ReactNode
} )
{
  return (
    <html lang="en">
      <body className={`${quicksand.className} dark`}>
        <Content children={children} />
      </body>
    </html>
  )
}
