import './globals.css'
import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import Content from './Content'
import { getServerSession } from 'next-auth'
import SessionProvider from './components/SessionProvider'


const quicksand = Quicksand( { subsets: ['latin'] } )

export const metadata: Metadata = {
  title: 'Applicant Tracker',
  description: 'Generated by create next app',
}

export default async function RootLayout ( {
  children,
}: {
  children: React.ReactNode
} )
{
  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={`${quicksand.className} dark`}>
        <SessionProvider session={session}>
          <Content children={children} />
        </SessionProvider>
      </body>
    </html>
  )
}
